### ISSUE TITLE
Small docstring missmatch in get_sos() and get_eos()

### ISSUE THREAD

**Issue by Lmoesinger** [lewistrotter/Phenolopy#1]
Just a minor typo:

According to the descriptions of [`get_sos()`](https://github.com/lewistrotter/Phenolopy/blob/main/scripts/phenolopy.py#L1176)  and [`get_eos()`](https://github.com/lewistrotter/Phenolopy/blob/main/scripts/phenolopy.py#L1513)), one possible method is `"stl_trendline"`. 
However, the code expects the methods to be called `"stl_trend"` (https://github.com/lewistrotter/Phenolopy/blob/main/scripts/phenolopy.py#L1392 and https://github.com/lewistrotter/Phenolopy/blob/main/scripts/phenolopy.py#L1729 , respectively). So one of the two strings should be adjusted.

Anyway, thanks a lot for this package, its really great!

**Comment by lewistrotter** [comment]
Thank you, fixed!
